import "./globals.css";

export const metadata = {
  title: "Lemon hive",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-[#172029] min-h-screen px-[30px] sm:px-[150px]">
        {children}
      </body>
    </html>
  );
}
